language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements.txt
    - cd ./src
    - python setup.py develop
    - cd ../
script:
    - python -c "import sys; opts = {1114111: 'ucs4', 65535: 'ucs2'}; print(opts.get(sys.maxunicode));"
    - cd ./test
    - py.test