language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements.txt
    - cd ./src
    - python setup.py develop
    - cd ../
script:
    - cd ./test
    - py.test